{"name": "test_with_incorrect_username", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Wrong password.' == 'User does not exist.'\n  - User does not exist.\n  + Wrong password.", "trace": "self = <Web.Tests.test_login.Test_Login object at 0x000002E904219C90>\n\n>   ???\nE   AssertionError: assert 'Wrong password.' == 'User does not exist.'\nE     - User does not exist.\nE     + Wrong password.\n\nC:\\Users\\user\\PycharmProjects\\Final Project\\Web\\Tests\\test_login.py:32: AssertionError"}, "description": "Verify login with an incorrect username and correct password", "steps": [{"name": "Opening the website", "status": "passed", "start": 1675538060345, "stop": 1675538060658}, {"name": "Clicking the element", "status": "passed", "parameters": [{"name": "locate", "value": "('xpath', \"//a[@id='login2']\")"}], "start": 1675538060658, "stop": 1675538060747}, {"name": "Clicking the element", "status": "passed", "parameters": [{"name": "locate", "value": "('xpath', \"//button[contains(text(),'Log in')]\")"}], "start": 1675538061520, "stop": 1675538061575}, {"name": "Read alert message", "status": "passed", "parameters": [{"name": "time", "value": "10"}], "start": 1675538061576, "stop": 1675538062093}], "start": 1675538060345, "stop": 1675538062094, "uuid": "e975dc27-86eb-4a65-bdbb-56504d96d30f", "historyId": "3c5c7f4c4a797be50c4a48e39bc030aa", "testCaseId": "53b097552b949f644fbe9dbbbf76836c", "fullName": "Tests.test_login.Test_Login#test_with_incorrect_username", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_Login"}, {"name": "host", "value": "mike"}, {"name": "thread", "value": "7176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login"}]}